name: arcgis_maps
description: ArcGIS Maps SDK for Flutter is a plugin for ArcGIS Maps SDK for Kotlin and ArcGIS Maps SDK for Swift (Not available) created by Ludycom S.A.S. Currently in beta, it is planned to be used in production, the plugin will allow users to use ArcGIS maps through a customizable and optimized widget.
version: 0.0.2
homepage: https://github.com/Ludycom/arcgis_maps_ludycom
repository: https://github.com/Ludycom/arcgis_maps_ludycom

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.15
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ludycom.arcgis_maps
        pluginClass: AGMLPlugin
      ios:
        pluginClass: AGMLPlugin
      some_platform:
        pluginClass: somePluginClass
